### ISSUE TITLE
Importing an HEIC image fails

### ISSUE THREAD

**Issue by ghost** [TobiZog/cinnamon-dynamic-wallpaper#6] opened 2023-10-04 14:05 UTC
I'm trying to import [this](https://dynamicwallpaper.club/wallpaper/ma10m2ab50s) HEIC image but the extension says "Input file is not an HEIF/AVIF file".

I've tried executing the extension by console like in issue #2, 

```bash
~/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/image-configurator$ python3 image-configurator.py 
Input file is not an HEIF/AVIF file
```

Tried with [another heic](https://dynamicwallpaper.club/wallpaper/la4wfuwtkg) from the same website with no luck either, but this time going steps further onto importing.

```bash
~/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/image-configurator$ python3 image-configurator.py 
File contains 16 images
Written to /home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/extracted/macOS Monterey-1.jpg
Written to /home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/extracted/macOS Monterey-2.jpg
Written to /home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/extracted/macOS Monterey-3.jpg
Written to /home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/extracted/macOS Monterey-4.jpg
Written to /home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/extracted/macOS Monterey-5.jpg
Written to /home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/extracted/macOS Monterey-6.jpg
Written to /home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/extracted/macOS Monterey-7.jpg
Written to /home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/extracted/macOS Monterey-8.jpg
Written to /home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/extracted/macOS Monterey-9.jpg
Written to /home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/extracted/macOS Monterey-10.jpg
Written to /home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/extracted/macOS Monterey-11.jpg
Written to /home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/extracted/macOS Monterey-12.jpg
Written to /home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/extracted/macOS Monterey-13.jpg
Written to /home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/extracted/macOS Monterey-14.jpg
Written to /home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/extracted/macOS Monterey-15.jpg
Written to /home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/extracted/macOS Monterey-16.jpg
```

This seemed to work apparently but the image is not applied in my desktop or listed in the 
 extension list.

If we assume the images are the problem, where are you getting those type of images? Or how do you create them?

EDIT: Using linux mint 21.2 Cinnamon edition.

**Comment by Arnproj** [comment] 2023-10-09 05:15
Hi,
i have the same problem. I can load the same .heic image but nothing appears on the desktop, previews don't work either.
Linux Mint 21.2 Cinnamon (Cinnamon 5.8.4).

**Comment by TobiZog** [comment] 2023-10-09 11:14
I've tested it with the same file and it worked for me. Did you have additional information, so I can reproduce the bug?

![image](https://github.com/TobiZog/cinnamon-dynamic-wallpaper/assets/67568441/3ef63060-c47e-4416-b29f-93d3c22f994e)

**Comment by Arnproj** [comment] 2023-10-09 11:44
thanks for the test. the file is in /home/arno/Images/Wallpapers/Dynamic for me.
should I import it from somewhere else?

the result for me :

![2023-10-09_13-42](https://github.com/TobiZog/cinnamon-dynamic-wallpaper/assets/147365816/8a57f72a-a83b-47e2-a25e-a3a9b3719ec8)

**Comment by TobiZog** [comment] 2023-10-09 11:53
> thanks for the test. the file is in /home/arno/Images/Wallpapers/Dynamic for me. should I import it from somewhere else?

The folder is wrong. The extension have to be placed here:
![image](https://github.com/TobiZog/cinnamon-dynamic-wallpaper/assets/67568441/27dc588d-b939-462f-be16-5b5066c70865)

I would recommend the extension manager of Cinnamon. In the "Download" tab is the latest version of the Cinnamon Dynamic Wallpaper available. Did you test this installation method?

**Comment by iru2x** [comment] 2023-10-09 21:12
> I've tested it with the same file and it worked for me. Did you have additional information, so I can reproduce the bug?

I don't want to look rude but I detailed every step I do when I import a HEIC image.
I don't know what else can I provide you.

Maybe if you try it on a fresh install on a VM you can reproduce same behaviour? Perhaps you have some packages we don't? Maybe is a python-related issue?

**Comment by TobiZog** [comment] 2023-10-10 09:57
> > I've tested it with the same file and it worked for me. Did you have additional information, so I can reproduce the bug?
> 
> I don't want to look rude but I detailed every step I do when I import a HEIC image. Please tell me whatever you need and I'll provide you.
> 
> Maybe if you try it on a fresh install on a VM you can reproduce same behaviour? Perhaps you have some packages we don't? Maybe is a python-related issue?
> 
> I'm having the same logs as @Arnproj.
> 
> Trying to import an HEIC:
> 
> ```
> 22:59:51	Main loop runs...
> 22:59:44	Set new image: file:///home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/selected/null
> 22:59:44	Location updated
> 22:59:43	Set new image: file:///home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/selected/null
> 22:59:43	Location updated
> 22:59:43	Set new image: file:///home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/selected/null
> 22:59:43	Location updated
> 22:59:43	Set new image: file:///home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/selected/null
> 22:59:43	Location updated
> 22:59:43	Set new image: file:///home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/selected/null
> 22:59:43	Location updated
> 22:59:43	Set new image: file:///home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/selected/null
> 22:59:43	Location updated
> 22:59:43	Set new image: file:///home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/selected/null
> 22:59:43	Location updated
> 22:59:43	Set new image: file:///home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/selected/null
> 22:59:43	Location updated
> 22:59:42	Set new image: file:///home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/selected/null
> 22:59:42	Location updated
> 22:58:51	Main loop runs...
> ```
> 
> Setting an already existing image from default installation ("gradient" in this case):
> 
> ```
> 23:13:51	Main loop runs...
> 23:13:38	Set new image: file:///home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/selected/9.jpg
> 23:13:38	Location updated
> 23:13:38	Set new image: file:///home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/selected/9.jpg
> 23:13:38	Location updated
> 23:13:38	Set new image: file:///home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/selected/9.jpg
> 23:13:38	Location updated
> 23:13:37	Set new image: file:///home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/selected/9.jpg
> 23:13:37	Location updated
> 23:13:37	Set new image: file:///home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/selected/9.jpg
> 23:13:37	Location updated
> 23:13:37	Set new image: file:///home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/selected/9.jpg
> 23:13:37	Location updated
> 23:13:37	Set new image: file:///home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/selected/9.jpg
> 23:13:37	Location updated
> 23:13:37	Set new image: file:///home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/selected/9.jpg
> 23:13:37	Location updated
> 23:13:37	Set new image: file:///home/user/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/selected/9.jpg
> 23:13:37	Location updated
> 23:12:51	Main loop runs...
> ```

Can you please send me the content of the config file? The "tv_logs" section is not necessary. You find it here: 
`/home/.config/cinnamon/spices/cinnamon-dynamic-wallpaper@TobiZog/cinnamon-dynamic-wallpaper@TobiZog.json`

Description:
The python script stores the selected images in the file, so the JavaScript extension can access the name of the right image (e.g. "etr_img_sunrise" contains the image, which will be displayed at sunrise).

**Comment by Arnproj** [comment] 2023-10-10 10:48
here is my file.

[cinnamon-dynamic-wallpaper@TobiZog.json](https://github.com/TobiZog/cinnamon-dynamic-wallpaper/files/12856156/cinnamon-dynamic-wallpaper%40TobiZog.json)

**Comment by iru2x** [comment] 2023-10-10 10:53
> Can you please send me the content of the config file? The "tv_logs" section is not necessary. You find it here: `/home/.config/cinnamon/spices/cinnamon-dynamic-wallpaper@TobiZog/cinnamon-dynamic-wallpaper@TobiZog.json`

[Here](https://pastebin.com/xb5quQDm) your are, sir :)

**Comment by TobiZog** [comment] 2023-10-10 15:50
They look booth correct. Could you please send me a screenshot of the contents in the selected images folder?

Location is: `~/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/selected/`

E.g.:
![image](https://github.com/TobiZog/cinnamon-dynamic-wallpaper/assets/67568441/988c01e3-2ed5-49c0-a9e9-a64852ee2579)

**Comment by iru2x** [comment] 2023-10-10 16:25
Okaaay...so:

![image](https://github.com/TobiZog/cinnamon-dynamic-wallpaper/assets/133756704/bb682567-66de-4b4c-a9f7-2b2f568ae5ea)

Once imported and clicked Apply it decompress the heic in this folder, but it doesn't apply the desktop background.
Later I'll check the verbose in console...

**Comment by iru2x** [comment] 2023-10-10 18:42
Both selected and extracted images folder looks good:

![image](https://github.com/TobiZog/cinnamon-dynamic-wallpaper/assets/133756704/0f5c5dcd-65e6-4cde-8e16-79446bd0ed69)

![image](https://github.com/TobiZog/cinnamon-dynamic-wallpaper/assets/133756704/87528aaf-b1f9-45d2-9ef0-9bf392ecfbea)

Done by console through `python3 image-configurator.py` and the output was clean.

**Comment by Arnproj** [comment] 2023-10-10 19:56
For me the problem seems to be here. No extract when i choose a .heic file.

![image](https://github.com/TobiZog/cinnamon-dynamic-wallpaper/assets/147365816/09889ea5-dcc2-4c22-ac0b-607d3da19a79)

**Comment by TobiZog** [comment] 2024-01-17 19:08
The issue is fixed with the latest commit. Version 2.0 coming in the next days. Thanks for your help!

**Closed by TobiZog** 2024-01-17 19:08 UTC
Labels: bug
