### ISSUE TITLE
Can't open image configuration on Cinnamon 6.0.2 Archlinux

### ISSUE THREAD

**Issue by carobinario** [TobiZog/cinnamon-dynamic-wallpaper#10] opened 2024-01-02 17:54 UTC
Hi,
I don't know if this issue is similar to #9  or not.

**Update**: This also happens on Linux Mint 21.3 beta / Cinnamon 6.0.3

I'm running Cinnamon 6.0.2 on EndavourOS (Archlinux) on Virtualbox. I can only configure partially cinnamon-dynamic. In fact if I click on Configuration / Image configurator, nothing happen. The same happen if i click on informations / (the two buttons) open Cinnamon Spices Website or open the repository.

Cinnamon extension window show an error in the Cynnamon Dynamic Wallpaper:

![screenshot](https://github.com/TobiZog/cinnamon-dynamic-wallpaper/assets/16922051/03f01e24-308f-468e-a243-a503ef0311ae)

Attached, you can find my [system configuration](https://github.com/TobiZog/cinnamon-dynamic-wallpaper/files/13812676/configuration.txt)

This is the Melange error log (Cinnamon 6.0.2 EndavourOS)

```
[error t=2024-01-02T18:27:00Z [TypeError: Soup.SessionSync is not a constructor]: Failed to evaluate 'init' function on extension: cinnamon-dynamic-wallpaper@TobiZog
trace t=2024-01-02T18:27:00Z 
<----------------
logError@/usr/share/cinnamon/js/ui/extension.js:143:17
finishExtensionLoad@/usr/share/cinnamon/js/ui/extensionSystem.js:70:19
_init/<@/usr/share/cinnamon/js/ui/extension.js:286:32
---------------->
error t=2024-01-02T18:27:00Z 
[cinnamon-dynamic-wallpaper@TobiZog]: Extension cinnamon-dynamic-wallpaper@TobiZog: Could not create extension object.
[cinnamon-dynamic-wallpaper@TobiZog]: Error importing extension.js from cinnamon-dynamic-wallpaper@TobiZog
trace t=2024-01-02T18:27:00Z 
<----------------
_init/<@/usr/share/cinnamon/js/ui/extension.js:287:23
---------------->
```
Error on Cinnamon 6.0.3 (Cinnamon 6.0.3 Linux Mint 21.3 beta).

```
error t=2024-01-02T19:05:29Z [TypeError: Soup.SessionSync is not a constructor]: Failed to evaluate 'init' function on extension: cinnamon-dynamic-wallpaper@TobiZog
trace t=2024-01-02T19:05:29Z 
<----------------
logError@/usr/share/cinnamon/js/ui/extension.js:143:17
finishExtensionLoad@/usr/share/cinnamon/js/ui/extensionSystem.js:70:19
_init/<@/usr/share/cinnamon/js/ui/extension.js:286:32
---------------->
error t=2024-01-02T19:05:30Z 
[cinnamon-dynamic-wallpaper@TobiZog]: Extension cinnamon-dynamic-wallpaper@TobiZog: Could not create extension object.
[cinnamon-dynamic-wallpaper@TobiZog]: Error importing extension.js from cinnamon-dynamic-wallpaper@TobiZog
trace t=2024-01-02T19:05:30Z 
<----------------
_init/<@/usr/share/cinnamon/js/ui/extension.js:287:23
---------------->
error t=2024-01-02T19:05:33Z xapp-status@cinnamon.org: Icon or image seems out of sync (:1.41

```
[Linux Mint beta configuration ](https://github.com/TobiZog/cinnamon-dynamic-wallpaper/files/13812872/configuration.linux.mint.beta.txt)

**Comment by TobiZog** [comment] 2024-01-16 17:37
The issue is fixed with Version 2.0. You can download the Beta right now or wait some days for the stable release.

**Closed by TobiZog** 2024-01-16 17:37 UTC
